version: "3"
services:
  db:
    image: mariadb
    volumes:
#      - ./mysql:/var/lib/mysql
      - ./init_docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_USER: example
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: example

  app:
    restart: always
    build: .
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on:
      - db

#
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8088:8080