# Generated by Django 4.0.2 on 2022-02-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=3)),
                ('upfront_commistion_rate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('trait_commistion_rate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
